// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFe3G9VrWeFIf1kCtmkAyVJec6pZIxO1U',
    appId: '1:700349548345:web:365b28339f2a6865284ae8',
    messagingSenderId: '700349548345',
    projectId: 'barber-shop-be4df',
    authDomain: 'barber-shop-be4df.firebaseapp.com',
    storageBucket: 'barber-shop-be4df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvXCD8xeG5pJ5h6AaHroU4cqujJK5ez8Q',
    appId: '1:700349548345:android:4f8b8ac0153d3a26284ae8',
    messagingSenderId: '700349548345',
    projectId: 'barber-shop-be4df',
    storageBucket: 'barber-shop-be4df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXQIAibUHVr7eXhqxNxKOz2dA_xOP_9mU',
    appId: '1:700349548345:ios:78f861201ce3cf06284ae8',
    messagingSenderId: '700349548345',
    projectId: 'barber-shop-be4df',
    storageBucket: 'barber-shop-be4df.firebasestorage.app',
    iosBundleId: 'com.example.barbershop',
  );
}
